-d D:\Users\kali\Documents\braeth_light\impl\gwsynthesis\braeth_light.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst D:\Users\kali\Documents\braeth_light\src\braeth_light.cst
-cfg D:\Users\kali\Documents\braeth_light\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
